on:
  push:
    branches:
      - main

  pull_request: {}

name: Upload

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        name: Cache node modules of yarn
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: add cr
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          wget -O $GITHUB_WORKSPACE/bin/cr http://repo.calcit-lang.org/binaries/linux/cr
          chmod +x $GITHUB_WORKSPACE/bin/cr
          wget -O $GITHUB_WORKSPACE/bin/bundle_calcit http://repo.calcit-lang.org/binaries/linux/bundle_calcit
          chmod +x $GITHUB_WORKSPACE/bin/bundle_calcit
          echo "::add-path::$GITHUB_WORKSPACE/bin"

      - name: "prepare modules"
        run: >
          mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
          && git clone https://github.com/Quatrefoil-GL/touch-control.git

      - name: "compiles to js"
        run: >
          bundle_calcit -1 -s web/
          && cr --emit-js -1

      - run: wasm-pack build -t web

      - run: yarn && yarn vite build --base=./

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.rsync_private_key}}
        with:
          flags: "-avzr --progress"
          options: ""
          ssh_options: ""
          src: "dist/*"
          dest: "rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
